# 1. Сборка (тяжелая часть)
FROM node:20-alpine AS build-stage
# Аргумент для передачи URL API при сборке
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 2. Раздача (очень легкая часть)
FROM nginx:stable-alpine
# Копируем только готовый результат из первого этапа
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Копируем конфиг Nginx (если нужно)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
# Команда запуска Nginx уже вшита в образ nginx:stable-alpine, 
# поэтому в docker-compose её писать не надо.
