services:
  market_frontend:
    image: europe-west3-docker.pkg.dev/${GCP_PROJECT_ID}/market-service-app/frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - market_network

networks:
  market_network:
    external: true