server {
    listen 80;
    server_name _;

    # 1. Отдаем фронтенд (React/Vue/и т.д.)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Проксируем запросы к Бэкенду
    location /api/ {
        # ВАЖНО: Слеш в конце обязателен! 
        # Если фронтенд запросит /api/users, Nginx отрежет "/api/" 
        # и отправит в бэкенд просто "/users".
        # market_backend - это имя сервиса из вашего второго docker-compose
        proxy_pass http://market_backend:4242/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 3. Открываем доступ к документации FastAPI
    location /docs {
        proxy_pass http://market_backend:4242/docs;
    }
    location /openapi.json {
        proxy_pass http://market_backend:4242/openapi.json;
    }
}