name: Frontend Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build and Push Frontend Image
        run: |
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app-repo/frontend:latest .
          docker push europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app-repo/frontend:latest

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/app
            gcloud auth configure-docker europe-west3-docker.pkg.dev -q
            docker compose pull frontend
            docker compose up -d frontend
            docker image prune -f